# These are supported funding model platforms

github: akshay2211
patreon: # Replace with a single Patreon username
open_collective: akshay-sharma
ko_fi: akshay2211
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ["https://xscode.com/akshay2211/piximagepicker"]
